import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight, Check, Layers3 } from "lucide-react";
import { getProjectBySlug, PROJECTS_DATA } from "@/data/projects";

export function generateStaticParams() { return PROJECTS_DATA.map(({ slug }) => ({ slug })); }

export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const project = await getProjectBySlug(slug);
  if (!project) notFound();
  return <main className="pb-20"><section className="hero-grid border-b border-border-subtle"><div className="container py-16 sm:py-24"><Link href="/projects" className="inline-flex items-center gap-2 text-sm text-text-secondary transition hover:text-brand"><ArrowLeft className="h-4 w-4" /> All work</Link><p className="eyebrow mt-12">{project.category}</p><h1 className="mt-4 max-w-4xl text-4xl font-semibold tracking-[-.05em] sm:text-6xl">{project.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-text-secondary">{project.summary}</p><div className="mt-9 flex flex-wrap gap-2">{project.technologies.map(tech => <span key={tech} className="rounded-full border border-border-strong px-3 py-1 font-mono text-2xs text-text-secondary">{tech}</span>)}</div></div></section><section className="container grid gap-4 py-8 sm:grid-cols-3">{project.metrics.map(metric => <div key={metric.label} className="rounded-xl border border-border bg-surface p-5"><p className="font-mono text-2xs uppercase tracking-wider text-text-muted">{metric.label}</p><p className="mt-2 text-lg font-semibold">{metric.value}</p></div>)}</section><section className="container grid gap-8 py-8 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-2xl border border-border bg-surface p-7 sm:p-9"><p className="eyebrow">The challenge</p><p className="mt-4 text-xl leading-8 text-text-primary">{project.problemStatement}</p><p className="eyebrow mt-10">The solution</p><p className="mt-4 leading-7 text-text-secondary">{project.architecturalOverview}</p></div><aside className="rounded-2xl border border-border bg-surface-inset p-7"><Layers3 className="h-5 w-5 text-brand" /><h2 className="mt-5 text-xl font-semibold">Key capabilities</h2><ul className="mt-5 space-y-4">{project.keyFeatures.map(feature => <li key={feature} className="flex gap-3 text-sm leading-6 text-text-secondary"><span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-brand/15 text-brand"><Check className="h-3 w-3" /></span>{feature}</li>)}</ul></aside></section><section className="container"><div className="rounded-2xl bg-brand p-8 text-white sm:p-12"><p className="font-mono text-2xs uppercase tracking-[.16em] text-white/70">Have a similar challenge?</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em]">Let&apos;s make it work for your business.</h2><Link href="/contact" className="mt-7 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-background">Start a conversation <ArrowUpRight className="h-4 w-4" /></Link></div></section></main>;
}
